#!/usr/bin/env python3
"""
UNVEILED - deterministic device-frame hero compositor (LS-CREATIVE-OWNERSHIP safe).

WHAT THIS IS
------------
Takes (a) a preview screenshot of the customer's built site and (b) a STATIC
device-frame PNG that has a defined "screen" rectangle, and composites the
screenshot into that rectangle -> one hero PNG. This is the "anticipation
payload": the reveal email leads with the customer's ACTUAL site sitting on a
premium device, so the preview begins the moment they open the email.

WHY IT IS BUILT THIS WAY (resource discipline / creative ownership)
-------------------------------------------------------------------
- DETERMINISTIC. Same screenshot + same frame -> byte-identical hero. It is a
  pure Pillow overlay (resize + paste + optional rounded-corner mask). There is
  NO per-customer image generation and NO AI art here, by rule.
- The frame ART is NOT generated by this engine or by Claude. Polished device
  frames are the CEO's to supply (LS-CREATIVE-OWNERSHIP: engineering only). The
  code-drawn frame in this file's self-test is a NEUTRAL FUNCTIONAL PLACEHOLDER
  so the pipeline can be wired + eyeballed before real frame art lands.

WHERE REAL FRAMES LIVE
----------------------
Drop the polished, high-quality device-frame PNGs (transparent outside the
screen area) at:
    Web Assets/device-frames/laptop.png
    Web Assets/device-frames/phone.png
Each needs a matching "screen rectangle" (see FRAMES below) describing where the
screenshot should sit, in that PNG's pixel coordinates. Until real art exists,
build_placeholder_frame() draws a plain frame at runtime so nothing blocks.

INTEGRATION HOOK (where the build worker should call this)
----------------------------------------------------------
In worker/build_worker.py, immediately AFTER a successful deploy() (the block
that does `url = deploy(slug, html)` then `update_lead(..., preview_url=url)`):
    1. Screenshot the deployed preview_url (headless browser) -> upload the PNG
       to public storage -> that public URL is preview_image_url.
    2. hero_path = build_hero_from_screenshot(local_png, frame="laptop")
       -> upload hero PNG -> that public URL is hero_image_url.
    3. update_lead(lead_id, {"preview_image_url": <url>, "hero_image_url": <url>})
Do NOT hand-edit build_worker.py here (avoids a merge conflict with the lead
engineer); this module is the callable + the exact hook is specified above and
in EMAIL-TRACK-REVIEW-2026-06-30.md. If a frame or screenshot is missing, the
reveal template already falls back to its inline browser+phone frame, and the
templates.ts backstop strips the empty {{hero_image_url}} token cleanly.

DEPENDENCY
----------
Pillow. If missing:  pip install Pillow --break-system-packages
"""

from __future__ import annotations

import os
from typing import Dict, Tuple

try:
    from PIL import Image, ImageDraw
except ImportError as e:  # pragma: no cover - surfaced clearly at call time
    raise SystemExit(
        "hero_composite requires Pillow. Install: pip install Pillow --break-system-packages"
    ) from e


# ---------------------------------------------------------------------------
# Frame registry. Each entry: the frame PNG path + the screen rectangle (the
# area, in the frame PNG's own pixels, where the screenshot is placed) as
# (left, top, right, bottom), + a corner radius applied to the pasted shot.
# When real frame art lands in Web Assets/device-frames/, update these boxes to
# match the actual screen opening in that art.
# ---------------------------------------------------------------------------
FRAMES: Dict[str, Dict] = {
    "laptop": {
        # Placeholder geometry: 1280x820 canvas, 16:10-ish screen inset.
        "size": (1280, 820),
        "screen": (150, 70, 1130, 690),
        "radius": 10,
        "asset": "Web Assets/device-frames/laptop.png",
    },
    "phone": {
        # Placeholder geometry: 520x1040 canvas, tall screen inset.
        "size": (520, 1040),
        "screen": (46, 96, 474, 944),
        "radius": 28,
        "asset": "Web Assets/device-frames/phone.png",
    },
}


def _rounded(img: "Image.Image", radius: int) -> "Image.Image":
    """Apply rounded corners to an RGBA image via an alpha mask. Deterministic."""
    if radius <= 0:
        return img
    img = img.convert("RGBA")
    mask = Image.new("L", img.size, 0)
    d = ImageDraw.Draw(mask)
    d.rounded_rectangle((0, 0, img.size[0] - 1, img.size[1] - 1), radius=radius, fill=255)
    out = Image.new("RGBA", img.size, (0, 0, 0, 0))
    out.paste(img, (0, 0), mask)
    return out


def _fit_cover(shot: "Image.Image", box: Tuple[int, int, int, int]) -> "Image.Image":
    """Resize a screenshot to COVER the screen box (crop overflow, keep top).

    'cover' keeps the hero looking full-bleed like a real device screen; we
    anchor to the top so the site's hero section stays visible.
    """
    bw, bh = box[2] - box[0], box[3] - box[1]
    sw, sh = shot.size
    scale = max(bw / sw, bh / sh)
    nw, nh = max(1, round(sw * scale)), max(1, round(sh * scale))
    shot = shot.resize((nw, nh), Image.LANCZOS)
    # center horizontally, anchor to top
    left = max(0, (nw - bw) // 2)
    return shot.crop((left, 0, left + bw, bh))


def build_placeholder_frame(frame: str = "laptop") -> "Image.Image":
    """Draw a NEUTRAL code-drawn device frame (RGBA, transparent outside).

    FUNCTIONAL PLACEHOLDER ONLY. Real polished frame art is CEO-supplied per
    LS-CREATIVE-OWNERSHIP; drop it at the asset path in FRAMES[frame]['asset'].
    """
    spec = FRAMES[frame]
    w, h = spec["size"]
    sx0, sy0, sx1, sy1 = spec["screen"]
    canvas = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(canvas)
    body_radius = 36 if frame == "phone" else 22
    # neutral graphite body
    d.rounded_rectangle((0, 0, w - 1, h - 1), radius=body_radius, fill=(28, 25, 23, 255))
    # screen well (slightly inset, near-black) so the pasted shot reads as a screen
    d.rounded_rectangle((sx0 - 6, sy0 - 6, sx1 + 6, sy1 + 6),
                        radius=spec["radius"] + 4, fill=(10, 10, 12, 255))
    if frame == "phone":
        # camera notch dot, purely cosmetic + neutral
        cx = w // 2
        d.ellipse((cx - 5, 40, cx + 5, 50), fill=(60, 60, 66, 255))
    return canvas


def _load_frame(frame: str) -> "Image.Image":
    """Load real frame art if present, else the placeholder. Repo-root relative."""
    spec = FRAMES[frame]
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    asset_path = os.path.join(repo_root, spec["asset"])
    if os.path.exists(asset_path):
        return Image.open(asset_path).convert("RGBA")
    return build_placeholder_frame(frame)


def build_hero_from_image(shot: "Image.Image", frame: str = "laptop") -> "Image.Image":
    """Composite a screenshot Image into the named frame's screen box. Deterministic."""
    if frame not in FRAMES:
        raise ValueError(f"unknown frame '{frame}'; known: {sorted(FRAMES)}")
    spec = FRAMES[frame]
    base = _load_frame(frame).copy()
    box = spec["screen"]
    fitted = _fit_cover(shot.convert("RGBA"), box)
    fitted = _rounded(fitted, spec["radius"])
    base.alpha_composite(fitted, dest=(box[0], box[1]))
    return base


def build_hero_from_screenshot(screenshot_path: str, out_path: str,
                               frame: str = "laptop") -> str:
    """Load a screenshot PNG from disk, composite into `frame`, save hero PNG.

    Returns out_path. This is the function the build worker calls after it
    screenshots the deployed preview. Deterministic: same inputs -> same bytes.
    """
    shot = Image.open(screenshot_path)
    hero = build_hero_from_image(shot, frame=frame)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    hero.save(out_path, format="PNG")
    return out_path


if __name__ == "__main__":
    # Self-test: composite a sample solid-color "screenshot" into the code-drawn
    # placeholder laptop + phone frames, write outputs so a human can eyeball
    # them. No network, no generation, fully deterministic.
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    out_dir = os.path.join(repo_root, "outputs")
    os.makedirs(out_dir, exist_ok=True)

    # fake screenshot: brand-purple top band + light body, so the composite is
    # obviously a "site" without needing a real capture.
    sample = Image.new("RGBA", (1200, 900), (250, 248, 245, 255))
    d = ImageDraw.Draw(sample)
    d.rectangle((0, 0, 1200, 150), fill=(108, 60, 224, 255))
    d.rectangle((60, 260, 1140, 300), fill=(28, 25, 23, 255))
    d.rectangle((60, 340, 720, 372), fill=(168, 162, 158, 255))
    sample_path = os.path.join(out_dir, "hero_selftest_screenshot.png")
    sample.save(sample_path)

    for fr in ("laptop", "phone"):
        out_path = os.path.join(out_dir, f"hero_selftest_{fr}.png")
        build_hero_from_screenshot(sample_path, out_path, frame=fr)
        print(f"wrote {out_path}")
    print("hero_composite self-test OK (placeholder frames; real art is CEO-supplied).")
